#!/usr/bin/env php
<?php

require_once('vendor/autoload.php');

define('SCRIPTS_ROOT', __DIR__);
define('LIBS_ROOT', SCRIPTS_ROOT . '/lib');

use Symfony\Component\Console\Application;

$application = new Application('Pusher', '0.1a');
$application->add(new Marks\Pusher\SubmitCommand());
$application->add(new Marks\Pusher\RegisterCommand());
$application->run();
